import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Profile from '@/components/organisms/Profile'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio - Jasper Bailey',
  description: 'Portfolio website generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"flex flex-col items-center justify-between lg:flex-row " + inter.className}>

        <Profile/>
        
        <section>
          {children}
        </section>
        
      </body>
    </html>
  )
}
