import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Footer from "../components/organisms/Footer"
import Header from "../components/organisms/Header"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio - Jasper Bailey',
  description: 'Portfolio website generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"flex flex-col min-h-screen justify-between items-center " + inter.className}>

        <Header/>

        <section>
          {children}
        </section>

        <Footer/>
        
      </body>
    </html>
  )
}
